export const IMAGES = {
    ic_SplashLogo: require("../Assets/Images/splash_logo.png"),
    ic_BackBlackIcon: require("../Assets/Images/splash_logo.png"),
    ic_MainImg: require("../Assets/Images/splash_logo.png"),
    bg_Intro_Top: require("../Assets/Images/intro_top.png"),
    bg_Intro_End: require("../Assets/Images/intro_end.png"),
    ic_Intro_QR: require("../Assets/Images/ic_Intro_QR.png"),
    ic_Arrow: require("../Assets/Images/ic_Arrow.png"),
    ic_Generate_QR: require("../Assets/Images/ic_Generate_QR.png"),
    ic_Scan_QR: require("../Assets/Images/ic_Scan_QR.png"),
    ic_History: require("../Assets/Images/ic_History.png"),
    ic_Text: require("../Assets/Images/ic_Text.png"),
    ic_Website: require("../Assets/Images/ic_Website.png"),
    ic_Wi_Fi: require("../Assets/Images/ic_Wi_Fi.png"),
    ic_Event: require("../Assets/Images/ic_Event.png"),
    ic_Contact: require("../Assets/Images/ic_Contact.png"),
    ic_Business: require("../Assets/Images/ic_Business.png"),
    ic_Location: require("../Assets/Images/ic_Location.png"),
    ic_Whatsapp: require("../Assets/Images/ic_Whatsapp.png"),
    ic_Email: require("../Assets/Images/ic_Email.png"),
    ic_Twitter: require("../Assets/Images/ic_Twitter.png"),
    ic_Instagram: require("../Assets/Images/ic_Instagram.png"),
    ic_Telephone: require("../Assets/Images/ic_Telephone.png"),
    ic_Line_Menu: require("../Assets/Images/ic_Line_Menu.png"),
    ic_Scan_History: require("../Assets/Images/ic_Scan_History.png"),
    bg_Background_Design: require("../Assets/Images/bg_Background_Design.png"),
    ic_Delete: require("../Assets/Images/ic_Delete.png"),
}