export const IMAGES = {
    ic_SplashLogo: require("../Assets/Images/splash_logo.png"),
    ic_BackBlackIcon: require("../Assets/Images/splash_logo.png"),
    ic_MainImg: require("../Assets/Images/splash_logo.png"),
    bg_Intro_Top: require("../Assets/Images/intro_top.png"),
    bg_Intro_End: require("../Assets/Images/intro_end.png"),
    ic_Intro_QR: require("../Assets/Images/ic_Intro_QR.png"),
    ic_Arrow: require("../Assets/Images/ic_Arrow.png"),
    ic_Generate_QR: require("../Assets/Images/ic_Generate_QR.png"),
    ic_Scan_QR: require("../Assets/Images/ic_Scan_QR.png"),
    ic_History: require("../Assets/Images/ic_History.png"),

    ic_Text_yl: require("../Assets/Images/ic_Text_yl.png"),
    ic_Website_yl: require("../Assets/Images/ic_Website_yl.png"),
    ic_Wi_Fi_yl: require("../Assets/Images/ic_Wi_Fi_yl.png"),
    ic_Event_yl: require("../Assets/Images/ic_Event_yl.png"),
    ic_Contact_yl: require("../Assets/Images/ic_Contact_yl.png"),
    ic_Business_yl: require("../Assets/Images/ic_Business_yl.png"),
    ic_Location_yl: require("../Assets/Images/ic_Location_yl.png"),
    ic_Whatsapp_yl: require("../Assets/Images/ic_Whatsapp_yl.png"),
    ic_Email_yl: require("../Assets/Images/ic_Email_yl.png"),
    ic_Twitter_yl: require("../Assets/Images/ic_Twitter_yl.png"),
    ic_Instagram_yl: require("../Assets/Images/ic_Instagram_yl.png"),
    ic_Telephone_yl: require("../Assets/Images/ic_Telephone_yl.png"),

    ic_Line_Menu: require("../Assets/Images/ic_Line_Menu.png"),
    ic_Scan_History: require("../Assets/Images/ic_Scan_History.png"),
    bg_Background_Design: require("../Assets/Images/bg_Background_Design.png"),
    ic_Delete: require("../Assets/Images/ic_Delete.png"),
    ic_Back: require("../Assets/Images/ic_Back.png"),
    ic_QR_History: require("../Assets/Images/ic_QR_History.png"),
    ic_Vibrate: require("../Assets/Images/ic_Vibrate.png"),
    ic_Beep: require("../Assets/Images/ic_Beep.png"),
    ic_Share: require("../Assets/Images/ic_Share.png"),
    ic_Privacy_Policy: require("../Assets/Images/ic_Privacy_Policy.png"),
    ic_Rate_Us: require("../Assets/Images/ic_Rate_Us.png"),
    ic_Share_Big: require("../Assets/Images/ic_Share_Big.png"),
    ic_Copy: require("../Assets/Images/ic_Copy.png"),

    ic_NFC_Tap: require("../Assets/Images/ic_NFC_Tap.png"),
    ic_Write_On_Nfc: require("../Assets/Images/ic_Write_On_Nfc.png"),
}