export const Colors = {
    RoyalPurple: '#5F5A8F',
    DefaultWhite: '#FFFFFF',
    DefaultGreenColor: '#3EA015',
    DefaultRedColor: "#DA2524",
    StatusYellowColor: "#FFC71B",
    BlushPink: "#E87AA3",
    DefaultBgColor: "#7e79a8ab",
    DefaultColor: "#8D2020",
    defaultRedColor: "red",
    Defaultblack: 'black',
    DarkGreyColor: '#FFFFFF',
    NormalGreyColor: '#FFFFFF',
    secondaryColor: '#FFFFFF',

    DefaultYellow: '#FDB623',
    CharcoalGray: "#333333",
    CharcoalGrayOpacity: "#525252",
    LightCharcoalGray: "#3E3E42",
    SoftSilver: "#D9D9D9",
    SoftSilverWithOpacity: 'rgba(217, 217, 217, 0.34)',
    NeutralSilver: "#A4A4A4",
};